### ISSUE TITLE
Passing the CRF output to an Embedding layer

### ISSUE THREAD

**Issue by deakkon** [howl-anderson/tf_crf_layer#2]
Hi Xiaoquan, 

thank you for your effort in putting this together. Although all the demos/examples work flawlessly (well, unless one uses _crf_viterbi_accuracy_ which generates errors). 

I am working on implementing https://arxiv.org/abs/1804.07847 for a joint NER/RE extraction and have a special use case want to combine the output of the CRF layer (which should be integers, batch_size*seq_lenght) and pass it on to an Embedding layer use that to support the training of the RE model:

 _We also use the entity tags as input to our relation extraction layer by learning label embeddings_

Could you maybe provide any insight on what I am doing wrong? Any help is greatly appreciated. 

Code snippet generating the error:
crf_out = CRF(self._n_tags, kernel_regularizer=l2(), name="NER_CRF", use_boundary=False)(model)
label_embeddings = Embedding(input_dim=self._n_tags,
                                     output_dim=self._label_dimension,
                                     input_length=self._seq_length,
                                     mask_zero=True,
                                     embeddings_initializer='he_normal',
                                     trainable=True,
                                     embeddings_regularizer=l2,
                                     name='RE_word_embeddings')(crf_out)

(_model_ is a concatenation of a BiLSTM over word and character WEs with masking)

My traceback:

Traceback (most recent call last):
  File "/anaconda3/envs/know-nlp/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 410, in enter
    yield
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 824, in __call__
    self._maybe_build(inputs)
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2146, in _maybe_build
    self.build(input_shapes)
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 306, in wrapper
    output_shape = fn(instance, input_shape)
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/embeddings.py", line 146, in build
    constraint=self.embeddings_constraint)
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 529, in add_weight
    aggregation=aggregation)
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py", line 712, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 126, in make_variable
    variable_shape = tensor_shape.TensorShape(shape)
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 718, in as_dimension
    return Dimension(value)
  File "/anaconda3/envs/know-nlp/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 193, in __init__
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

**Comment by deakkon** [comment]
Terribly sorry for this. You can delete this issue; it turned out it was a silly syntax mistake on my part.

**Comment by touhi99** [comment]
Hi @deakkon , I am also facing the same issue (probably not related with the design with this CRF, I am using keras-contrib CRF). Would you tell how'd you solve the issue? (or was it the problem in the parameter?) 

Thanks!

**Comment by deakkon** [comment]
As mentioned above, in my case it was a silly syntax error (forgot to remove a _,_ which then turned the integers into a tuple). 

If you are using keras-contrib then I would suggest you ask the question on their git; they would probably be of more service (especially if it's not a silly mistake like mine). But keras-contrib CRF should be quite straightforward to use; have used it myself numerous times and had no issues with it.
