### ISSUE TITLE
Getting into AttributeError: 'Tensor' object has no attribute '_keras_history'

### ISSUE THREAD

**Issue by sathish331977** [howl-anderson/tf_crf_layer#5]
WARNING:tensorflow:`load_weights_on_restart` argument is deprecated. Please use `model.load_weights()` for loading weights before the start of `model.fit()`.
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 439, in compile
    masks=self._prepare_output_masks())
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2004, in _handle_metrics
    target, output, output_mask))
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1955, in _handle_per_output_metrics
    metric_fn, y_true, y_pred, weights=weights, mask=mask)
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 1155, in call_metric_function
    return metric_fn(y_true, y_pred, sample_weight=weights)
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 196, in __call__
    replica_local_fn, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\distribute\distributed_training_utils.py", line 1135, in call_replica_local_fn
    return fn(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 179, in replica_local_fn
    update_op = self.update_state(*args, **kwargs)  # pylint: disable=not-callable
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\utils\metrics_utils.py", line 76, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 587, in update_state
    matches = self._fn(y_true, y_pred, **self._fn_kwargs)
  File "C:\Users\gsathis\PycharmProjects\CondaTensorFlow\tf_crf_layer\metrics\crf_accuracy.py", line 23, in crf_viterbi_accuracy
    crf, idx = y_pred._keras_history[:2]
AttributeError: 'Tensor' object has no attribute '_keras_history'

**Comment by sathish331977** [comment]
i think i used wrong examples ,please ignore
